// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamGameStatistics.Data;

namespace SteamGameStatistics.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SteamGameStatistics.Data.DAOs.PlayerDao", b =>
                {
                    b.Property<string>("Steamid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarMedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CommunityVisibilityState")
                        .HasColumnType("bigint");

                    b.Property<long>("Lastlogoff")
                        .HasColumnType("bigint");

                    b.Property<string>("LocCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocStateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonaState")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonaStateFlags")
                        .HasColumnType("bigint");

                    b.Property<string>("PrimaryClanid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Profilestate")
                        .HasColumnType("bigint");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeCreated")
                        .HasColumnType("bigint");

                    b.HasKey("Steamid");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
